DOCKERCOMPOSE := docker compose

DOCKERCOMPOSE_API := api
DOCKERCOMPOSE_MIGRATE_UP := migrate-up
DOCKERCOMPOSE_MIGRATE_DOWN := migrate-down
DOCKERCOMPOSE_POSTGRES := postgres
DOCKERCOMPOSE_REDIS := redis
DOCKERCOMPOSE_GORSE := gorse
DOCKERCOMPOSE_CRAWLER_SCHEDULE := gorse

RUN_API := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_API)
RUN_MIGRATE_UP := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_MIGRATE_UP)
RUN_MIGRATE_DOWN := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_MIGRATE_DOWN)
RUN_POSTGRES := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_POSTGRES)
RUN_REDIS := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_REDIS)
RUN_GORSE := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_GORSE)
RUN_CRAWLER_SCHEDULE := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_CRAWLER_SCHEDULE)

RUN := $(DOCKERCOMPOSE) up -d

STOP_API := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSE_API) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_API)
STOP_MIGRATE := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSE_MIGRATE) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_MIGRATE)
STOP_POSTGRES := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSE_POSTGRES) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_POSTGRES)
STOP_REDIS := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSE_REDIS) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_REDIS)
STOP_REDIS := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSE_GORSE) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_GORSE)
STOP_CRAWLER_SCHEDULE := $(DOCKERCOMPOSE) stop $(DOCKERCOMPOSE_CRAWLER_SCHEDULE) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_CRAWLER_SCHEDULE)

.PHONY: run
run:
	$(RUN_POSTGRES)
	$(RUN_REDIS)
	sleep 1
	$(RUN_CRAWLER_SCHEDULE)
	$(RUN_GORSE)
	$(RUN_API)

.PHONY: run-build
run-build:
	$(RUN_POSTGRES)
	$(RUN_REDIS)
	sleep 1
	$(RUN_CRAWLER_SCHEDULE) --build
	$(RUN_GORSE) --build
	$(RUN_API) --build

.PHONY: stop
stop:
	$(STOP_API)
	$(STOP_GORSE)
	$(STOP_POSTGRES)
	$(STOP_CRAWLER_SCHEDULE)
	$(STOP_REDIS)

.PHONY: run-migrate-up
run-migrate-up:
	$(RUN_POSTGRES)
	$(RUN_REDIS)
	sleep 1
	$(RUN_MIGRATE_UP) --build

.PHONY: run-migrate-down
run-migrate-down:
	$(RUN_POSTGRES)
	$(RUN_REDIS)
	sleep 1
	$(RUN_MIGRATE_DOWN) --build

.PHONY: run-db
run-db:
	$(RUN_POSTGRES)
	$(RUN_REDIS)

.PHONY: run-system
run-system:
	$(RUN_POSTGRES)
	$(RUN_REDIS)
	$(RUN_GORSE)
