Environment = "development" # "production" or "development"

[Database]
    User = "postgres"
    Password = "123456"
    Name = "postgres"
    Host = "localhost"
    Port = "5433"

[Redis]
    Password = ""
    Name = "redis"
    Host = "redis"
    Port = "6379"
