Environment = "development" # "production" or "development"

[Database]
User = "postgres"
Password = "123456"
Name = "postgres"
Host = "postgres"
Port = "5432"

[Redis]
Password = ""
Name = "redis"
Host = "redis"
Port = "6379"

[Recommender]
Host = "gorse"
Port = "8088"