// Code generated by BobGen psql v0.21.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"encoding/json"
	"time"

	models "core/internal/content/bob"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker"
	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

type NewsInforMod interface {
	Apply(*NewsInforTemplate)
}

type NewsInforModFunc func(*NewsInforTemplate)

func (f NewsInforModFunc) Apply(n *NewsInforTemplate) {
	f(n)
}

type NewsInforModSlice []NewsInforMod

func (mods NewsInforModSlice) Apply(n *NewsInforTemplate) {
	for _, f := range mods {
		f.Apply(n)
	}
}

// NewsInforTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type NewsInforTemplate struct {
	ID           func() string
	Name         func() string
	Slug         func() string
	Link         func() null.Val[string]
	Description  func() string
	FeatureImage func() string
	Title        func() string
	Content      func() null.Val[string]
	Author       func() null.Val[string]
	Category     func() types.JSON[json.RawMessage]
	VideoURL     func() null.Val[string]
	CreatedAt    func() time.Time
	UpdatedAt    func() time.Time
	Labels       func() null.Val[pq.StringArray]

	f *factory
}

// Apply mods to the NewsInforTemplate
func (o *NewsInforTemplate) Apply(mods ...NewsInforMod) {
	for _, mod := range mods {
		mod.Apply(o)
	}
}

// toModel returns an *models.NewsInfor
// this does nothing with the relationship templates
func (o NewsInforTemplate) toModel() *models.NewsInfor {
	m := &models.NewsInfor{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Slug != nil {
		m.Slug = o.Slug()
	}
	if o.Link != nil {
		m.Link = o.Link()
	}
	if o.Description != nil {
		m.Description = o.Description()
	}
	if o.FeatureImage != nil {
		m.FeatureImage = o.FeatureImage()
	}
	if o.Title != nil {
		m.Title = o.Title()
	}
	if o.Content != nil {
		m.Content = o.Content()
	}
	if o.Author != nil {
		m.Author = o.Author()
	}
	if o.Category != nil {
		m.Category = o.Category()
	}
	if o.VideoURL != nil {
		m.VideoURL = o.VideoURL()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}
	if o.Labels != nil {
		m.Labels = o.Labels()
	}

	return m
}

// toModels returns an models.NewsInforSlice
// this does nothing with the relationship templates
func (o NewsInforTemplate) toModels(number int) models.NewsInforSlice {
	m := make(models.NewsInforSlice, number)

	for i := range m {
		m[i] = o.toModel()
	}

	return m
}

// setModelRels creates and sets the relationships on *models.NewsInfor
// according to the relationships in the template. Nothing is inserted into the db
func (t NewsInforTemplate) setModelRels(o *models.NewsInfor) {}

// BuildSetter returns an *models.NewsInforSetter
// this does nothing with the relationship templates
func (o NewsInforTemplate) BuildSetter() *models.NewsInforSetter {
	m := &models.NewsInforSetter{}

	if o.ID != nil {
		m.ID = omit.From(o.ID())
	}
	if o.Name != nil {
		m.Name = omit.From(o.Name())
	}
	if o.Slug != nil {
		m.Slug = omit.From(o.Slug())
	}
	if o.Link != nil {
		m.Link = omitnull.FromNull(o.Link())
	}
	if o.Description != nil {
		m.Description = omit.From(o.Description())
	}
	if o.FeatureImage != nil {
		m.FeatureImage = omit.From(o.FeatureImage())
	}
	if o.Title != nil {
		m.Title = omit.From(o.Title())
	}
	if o.Content != nil {
		m.Content = omitnull.FromNull(o.Content())
	}
	if o.Author != nil {
		m.Author = omitnull.FromNull(o.Author())
	}
	if o.Category != nil {
		m.Category = omit.From(o.Category())
	}
	if o.VideoURL != nil {
		m.VideoURL = omitnull.FromNull(o.VideoURL())
	}
	if o.CreatedAt != nil {
		m.CreatedAt = omit.From(o.CreatedAt())
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = omit.From(o.UpdatedAt())
	}
	if o.Labels != nil {
		m.Labels = omitnull.FromNull(o.Labels())
	}

	return m
}

// BuildManySetter returns an []*models.NewsInforSetter
// this does nothing with the relationship templates
func (o NewsInforTemplate) BuildManySetter(number int) []*models.NewsInforSetter {
	m := make([]*models.NewsInforSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.NewsInfor
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use NewsInforTemplate.Create
func (o NewsInforTemplate) Build() *models.NewsInfor {
	m := o.toModel()
	o.setModelRels(m)

	return m
}

// BuildMany returns an models.NewsInforSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use NewsInforTemplate.CreateMany
func (o NewsInforTemplate) BuildMany(number int) models.NewsInforSlice {
	m := make(models.NewsInforSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableNewsInfor(m *models.NewsInforSetter) {
	if m.ID.IsUnset() {
		m.ID = omit.From(random[string](nil))
	}
	if m.Name.IsUnset() {
		m.Name = omit.From(random[string](nil))
	}
	if m.Slug.IsUnset() {
		m.Slug = omit.From(random[string](nil))
	}
	if m.Description.IsUnset() {
		m.Description = omit.From(random[string](nil))
	}
	if m.FeatureImage.IsUnset() {
		m.FeatureImage = omit.From(random[string](nil))
	}
	if m.Title.IsUnset() {
		m.Title = omit.From(random[string](nil))
	}
	if m.Category.IsUnset() {
		m.Category = omit.From(random[types.JSON[json.RawMessage]](nil))
	}
	if m.CreatedAt.IsUnset() {
		m.CreatedAt = omit.From(random[time.Time](nil))
	}
	if m.UpdatedAt.IsUnset() {
		m.UpdatedAt = omit.From(random[time.Time](nil))
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.NewsInfor
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *NewsInforTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.NewsInfor) (context.Context, error) {
	var err error

	return ctx, err
}

// Create builds a newsInfor and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *NewsInforTemplate) Create(ctx context.Context, exec bob.Executor) (*models.NewsInfor, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// create builds a newsInfor and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *NewsInforTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.NewsInfor, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableNewsInfor(opt)

	m, err := models.NewsInforsTable.Insert(ctx, exec, opt)
	if err != nil {
		return ctx, nil, err
	}
	ctx = newsInforCtx.WithValue(ctx, m)

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple newsInfors and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o NewsInforTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.NewsInforSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// createMany builds multiple newsInfors and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o NewsInforTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.NewsInforSlice, error) {
	var err error
	m := make(models.NewsInforSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// NewsInfor has methods that act as mods for the NewsInforTemplate
var NewsInforMods newsInforMods

type newsInforMods struct{}

func (m newsInforMods) RandomizeAllColumns(f *faker.Faker) NewsInforMod {
	return NewsInforModSlice{
		NewsInforMods.RandomID(f),
		NewsInforMods.RandomName(f),
		NewsInforMods.RandomSlug(f),
		NewsInforMods.RandomLink(f),
		NewsInforMods.RandomDescription(f),
		NewsInforMods.RandomFeatureImage(f),
		NewsInforMods.RandomTitle(f),
		NewsInforMods.RandomContent(f),
		NewsInforMods.RandomAuthor(f),
		NewsInforMods.RandomCategory(f),
		NewsInforMods.RandomVideoURL(f),
		NewsInforMods.RandomCreatedAt(f),
		NewsInforMods.RandomUpdatedAt(f),
		NewsInforMods.RandomLabels(f),
	}
}

// Set the model columns to this value
func (m newsInforMods) ID(val string) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m newsInforMods) IDFunc(f func() string) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m newsInforMods) UnsetID() NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m newsInforMods) RandomID(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.ID = func() string {
			return random[string](f)
		}
	})
}

func (m newsInforMods) ensureID(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		if o.ID != nil {
			return
		}

		o.ID = func() string {
			return random[string](f)
		}
	})
}

// Set the model columns to this value
func (m newsInforMods) Name(val string) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m newsInforMods) NameFunc(f func() string) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m newsInforMods) UnsetName() NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m newsInforMods) RandomName(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Name = func() string {
			return random[string](f)
		}
	})
}

func (m newsInforMods) ensureName(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		if o.Name != nil {
			return
		}

		o.Name = func() string {
			return random[string](f)
		}
	})
}

// Set the model columns to this value
func (m newsInforMods) Slug(val string) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Slug = func() string { return val }
	})
}

// Set the Column from the function
func (m newsInforMods) SlugFunc(f func() string) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Slug = f
	})
}

// Clear any values for the column
func (m newsInforMods) UnsetSlug() NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Slug = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m newsInforMods) RandomSlug(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Slug = func() string {
			return random[string](f)
		}
	})
}

func (m newsInforMods) ensureSlug(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		if o.Slug != nil {
			return
		}

		o.Slug = func() string {
			return random[string](f)
		}
	})
}

// Set the model columns to this value
func (m newsInforMods) Link(val null.Val[string]) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Link = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m newsInforMods) LinkFunc(f func() null.Val[string]) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Link = f
	})
}

// Clear any values for the column
func (m newsInforMods) UnsetLink() NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Link = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m newsInforMods) RandomLink(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Link = func() null.Val[string] {
			return randomNull[string](f)
		}
	})
}

func (m newsInforMods) ensureLink(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		if o.Link != nil {
			return
		}

		o.Link = func() null.Val[string] {
			return randomNull[string](f)
		}
	})
}

// Set the model columns to this value
func (m newsInforMods) Description(val string) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Description = func() string { return val }
	})
}

// Set the Column from the function
func (m newsInforMods) DescriptionFunc(f func() string) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Description = f
	})
}

// Clear any values for the column
func (m newsInforMods) UnsetDescription() NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Description = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m newsInforMods) RandomDescription(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Description = func() string {
			return random[string](f)
		}
	})
}

func (m newsInforMods) ensureDescription(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		if o.Description != nil {
			return
		}

		o.Description = func() string {
			return random[string](f)
		}
	})
}

// Set the model columns to this value
func (m newsInforMods) FeatureImage(val string) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.FeatureImage = func() string { return val }
	})
}

// Set the Column from the function
func (m newsInforMods) FeatureImageFunc(f func() string) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.FeatureImage = f
	})
}

// Clear any values for the column
func (m newsInforMods) UnsetFeatureImage() NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.FeatureImage = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m newsInforMods) RandomFeatureImage(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.FeatureImage = func() string {
			return random[string](f)
		}
	})
}

func (m newsInforMods) ensureFeatureImage(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		if o.FeatureImage != nil {
			return
		}

		o.FeatureImage = func() string {
			return random[string](f)
		}
	})
}

// Set the model columns to this value
func (m newsInforMods) Title(val string) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Title = func() string { return val }
	})
}

// Set the Column from the function
func (m newsInforMods) TitleFunc(f func() string) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Title = f
	})
}

// Clear any values for the column
func (m newsInforMods) UnsetTitle() NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Title = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m newsInforMods) RandomTitle(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Title = func() string {
			return random[string](f)
		}
	})
}

func (m newsInforMods) ensureTitle(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		if o.Title != nil {
			return
		}

		o.Title = func() string {
			return random[string](f)
		}
	})
}

// Set the model columns to this value
func (m newsInforMods) Content(val null.Val[string]) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Content = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m newsInforMods) ContentFunc(f func() null.Val[string]) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Content = f
	})
}

// Clear any values for the column
func (m newsInforMods) UnsetContent() NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Content = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m newsInforMods) RandomContent(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Content = func() null.Val[string] {
			return randomNull[string](f)
		}
	})
}

func (m newsInforMods) ensureContent(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		if o.Content != nil {
			return
		}

		o.Content = func() null.Val[string] {
			return randomNull[string](f)
		}
	})
}

// Set the model columns to this value
func (m newsInforMods) Author(val null.Val[string]) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Author = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m newsInforMods) AuthorFunc(f func() null.Val[string]) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Author = f
	})
}

// Clear any values for the column
func (m newsInforMods) UnsetAuthor() NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Author = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m newsInforMods) RandomAuthor(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Author = func() null.Val[string] {
			return randomNull[string](f)
		}
	})
}

func (m newsInforMods) ensureAuthor(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		if o.Author != nil {
			return
		}

		o.Author = func() null.Val[string] {
			return randomNull[string](f)
		}
	})
}

// Set the model columns to this value
func (m newsInforMods) Category(val types.JSON[json.RawMessage]) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Category = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m newsInforMods) CategoryFunc(f func() types.JSON[json.RawMessage]) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Category = f
	})
}

// Clear any values for the column
func (m newsInforMods) UnsetCategory() NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Category = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m newsInforMods) RandomCategory(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Category = func() types.JSON[json.RawMessage] {
			return random[types.JSON[json.RawMessage]](f)
		}
	})
}

func (m newsInforMods) ensureCategory(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		if o.Category != nil {
			return
		}

		o.Category = func() types.JSON[json.RawMessage] {
			return random[types.JSON[json.RawMessage]](f)
		}
	})
}

// Set the model columns to this value
func (m newsInforMods) VideoURL(val null.Val[string]) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.VideoURL = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m newsInforMods) VideoURLFunc(f func() null.Val[string]) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.VideoURL = f
	})
}

// Clear any values for the column
func (m newsInforMods) UnsetVideoURL() NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.VideoURL = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m newsInforMods) RandomVideoURL(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.VideoURL = func() null.Val[string] {
			return randomNull[string](f)
		}
	})
}

func (m newsInforMods) ensureVideoURL(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		if o.VideoURL != nil {
			return
		}

		o.VideoURL = func() null.Val[string] {
			return randomNull[string](f)
		}
	})
}

// Set the model columns to this value
func (m newsInforMods) CreatedAt(val time.Time) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m newsInforMods) CreatedAtFunc(f func() time.Time) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m newsInforMods) UnsetCreatedAt() NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m newsInforMods) RandomCreatedAt(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.CreatedAt = func() time.Time {
			return random[time.Time](f)
		}
	})
}

func (m newsInforMods) ensureCreatedAt(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		if o.CreatedAt != nil {
			return
		}

		o.CreatedAt = func() time.Time {
			return random[time.Time](f)
		}
	})
}

// Set the model columns to this value
func (m newsInforMods) UpdatedAt(val time.Time) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m newsInforMods) UpdatedAtFunc(f func() time.Time) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m newsInforMods) UnsetUpdatedAt() NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m newsInforMods) RandomUpdatedAt(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.UpdatedAt = func() time.Time {
			return random[time.Time](f)
		}
	})
}

func (m newsInforMods) ensureUpdatedAt(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		if o.UpdatedAt != nil {
			return
		}

		o.UpdatedAt = func() time.Time {
			return random[time.Time](f)
		}
	})
}

// Set the model columns to this value
func (m newsInforMods) Labels(val null.Val[pq.StringArray]) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Labels = func() null.Val[pq.StringArray] { return val }
	})
}

// Set the Column from the function
func (m newsInforMods) LabelsFunc(f func() null.Val[pq.StringArray]) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Labels = f
	})
}

// Clear any values for the column
func (m newsInforMods) UnsetLabels() NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Labels = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m newsInforMods) RandomLabels(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		o.Labels = func() null.Val[pq.StringArray] {
			return randomNull[pq.StringArray](f)
		}
	})
}

func (m newsInforMods) ensureLabels(f *faker.Faker) NewsInforMod {
	return NewsInforModFunc(func(o *NewsInforTemplate) {
		if o.Labels != nil {
			return
		}

		o.Labels = func() null.Val[pq.StringArray] {
			return randomNull[pq.StringArray](f)
		}
	})
}
