// Code generated by BobGen psql v0.21.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

type MatchStatus string

// Enum values for MatchStatus
const (
	MatchStatusPending  MatchStatus = "pending"
	MatchStatusFinished MatchStatus = "finished"
	MatchStatusDelay    MatchStatus = "delay"
	MatchStatusCanceled MatchStatus = "canceled"
	MatchStatusLive     MatchStatus = "live"
)

func AllMatchStatus() []MatchStatus {
	return []MatchStatus{
		MatchStatusPending,
		MatchStatusFinished,
		MatchStatusDelay,
		MatchStatusCanceled,
		MatchStatusLive,
	}
}
