// Code generated by BobGen psql v0.21.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"

	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var TableNames = struct {
	Feedbacks       string
	GooseDBVersions string
	Items           string
	Matchs          string
	NewsInfors      string
	Teams           string
	Tournaments     string
	Users           string
}{
	Feedbacks:       "feedback",
	GooseDBVersions: "goose_db_version",
	Items:           "items",
	Matchs:          "matchs",
	NewsInfors:      "news_infor",
	Teams:           "teams",
	Tournaments:     "tournaments",
	Users:           "users",
}

var ColumnNames = struct {
	Feedbacks       feedbackColumnNames
	GooseDBVersions gooseDBVersionColumnNames
	Items           itemColumnNames
	Matchs          matchColumnNames
	NewsInfors      newsInforColumnNames
	Teams           teamColumnNames
	Tournaments     tournamentColumnNames
	Users           userColumnNames
}{
	Feedbacks: feedbackColumnNames{
		FeedbackType: "feedback_type",
		UserID:       "user_id",
		ItemID:       "item_id",
		TimeStamp:    "time_stamp",
		Comment:      "comment",
	},
	GooseDBVersions: gooseDBVersionColumnNames{
		ID:        "id",
		VersionID: "version_id",
		IsApplied: "is_applied",
		Tstamp:    "tstamp",
	},
	Items: itemColumnNames{
		ItemID:     "item_id",
		IsHidden:   "is_hidden",
		Categories: "categories",
		TimeStamp:  "time_stamp",
		Labels:     "labels",
		Comment:    "comment",
	},
	Matchs: matchColumnNames{
		ID:           "id",
		Name:         "name",
		Slug:         "slug",
		Date:         "date",
		Timestamp:    "timestamp",
		HomeRedCards: "home_red_cards",
		AwayRedCards: "away_red_cards",
		HomeID:       "home_id",
		AwayID:       "away_id",
		TournamentID: "tournament_id",
		Scores:       "scores",
		WinCode:      "win_code",
		MatchStatus:  "match_status",
		SportType:    "sport_type",
		HasLineup:    "has_lineup",
		HasTracker:   "has_tracker",
		IsFeatured:   "is_featured",
		ThumbnailURL: "thumbnail_url",
		IsLive:       "is_live",
		LiveTracker:  "live_tracker",
		CreatedAt:    "created_at",
		UpdatedAt:    "updated_at",
	},
	NewsInfors: newsInforColumnNames{
		ID:           "id",
		Name:         "name",
		Slug:         "slug",
		Link:         "link",
		Description:  "description",
		FeatureImage: "feature_image",
		Title:        "title",
		Content:      "content",
		Author:       "author",
		Category:     "category",
		VideoURL:     "video_url",
		CreatedAt:    "created_at",
		UpdatedAt:    "updated_at",
		Labels:       "labels",
	},
	Teams: teamColumnNames{
		ID:        "id",
		Name:      "name",
		ShortName: "short_name",
		Gender:    "gender",
		NameCode:  "name_code",
		Logo:      "logo",
		Slug:      "slug",
		CreatedAt: "created_at",
		UpdatedAt: "updated_at",
	},
	Tournaments: tournamentColumnNames{
		ID:         "id",
		Name:       "name",
		Slug:       "slug",
		Logo:       "logo",
		IsFeatured: "is_featured",
		Priority:   "priority",
		CreatedAt:  "created_at",
		UpdatedAt:  "updated_at",
	},
	Users: userColumnNames{
		UserID:    "user_id",
		Labels:    "labels",
		Subscribe: "subscribe",
		Comment:   "comment",
	},
}

var (
	SelectWhere = Where[*dialect.SelectQuery]()
	InsertWhere = Where[*dialect.InsertQuery]()
	UpdateWhere = Where[*dialect.UpdateQuery]()
	DeleteWhere = Where[*dialect.DeleteQuery]()
)

func Where[Q psql.Filterable]() struct {
	Feedbacks       feedbackWhere[Q]
	GooseDBVersions gooseDBVersionWhere[Q]
	Items           itemWhere[Q]
	Matchs          matchWhere[Q]
	NewsInfors      newsInforWhere[Q]
	Teams           teamWhere[Q]
	Tournaments     tournamentWhere[Q]
	Users           userWhere[Q]
} {
	return struct {
		Feedbacks       feedbackWhere[Q]
		GooseDBVersions gooseDBVersionWhere[Q]
		Items           itemWhere[Q]
		Matchs          matchWhere[Q]
		NewsInfors      newsInforWhere[Q]
		Teams           teamWhere[Q]
		Tournaments     tournamentWhere[Q]
		Users           userWhere[Q]
	}{
		Feedbacks:       FeedbackWhere[Q](),
		GooseDBVersions: GooseDBVersionWhere[Q](),
		Items:           ItemWhere[Q](),
		Matchs:          MatchWhere[Q](),
		NewsInfors:      NewsInforWhere[Q](),
		Teams:           TeamWhere[Q](),
		Tournaments:     TournamentWhere[Q](),
		Users:           UserWhere[Q](),
	}
}

var (
	SelectJoins = getJoins[*dialect.SelectQuery]
	UpdateJoins = getJoins[*dialect.UpdateQuery]
	DeleteJoins = getJoins[*dialect.DeleteQuery]
)

type joinSet[Q any] struct {
	InnerJoin Q
	LeftJoin  Q
	RightJoin Q
}

type joins[Q dialect.Joinable] struct {
	Matchs      joinSet[matchRelationshipJoins[Q]]
	Teams       joinSet[teamRelationshipJoins[Q]]
	Tournaments joinSet[tournamentRelationshipJoins[Q]]
}

func getJoins[Q dialect.Joinable](ctx context.Context) joins[Q] {
	return joins[Q]{
		Matchs:      matchsJoin[Q](ctx),
		Teams:       teamsJoin[Q](ctx),
		Tournaments: tournamentsJoin[Q](ctx),
	}
}
