// Code generated by BobGen psql v0.21.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"encoding/json"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/types"
)

// News is an object representing the database table.
type NewsType struct {
	ID           string                      `db:"id,pk" `
	Name         string                      `db:"name" `
	Slug         string                      `db:"slug" `
	Link         string                      `db:"link" `
	Description  string                      `db:"description" `
	FeatureImage string                      `db:"feature_image" `
	Title        string                      `db:"title" `
	Content      null.Val[string]            `db:"content" `
	Author       null.Val[string]            `db:"author" `
	Category     types.JSON[json.RawMessage] `db:"category" `
	VideoURL     null.Val[string]            `db:"video_url" `
	CreatedAt    time.Time                   `db:"created_at" `
	UpdatedAt    time.Time                   `db:"updated_at" `
}

// NewsSlice is an alias for a slice of pointers to News.
// This should almost always be used instead of []*News.
type NewsSlice []*NewsType

// NewsTable contains methods to work with the news table
var NewsTable = psql.NewTablex[*NewsType, NewsSlice, *NewsSetter]("", "news")

// NewsQuery is a query on the news table
type NewsQuery = *psql.TableQuery[*NewsType, NewsSlice, *NewsSetter]

// NewsStmt is a prepared statment on news
type NewsStmt = bob.QueryStmt[*NewsType, NewsSlice]

// NewsSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type NewsSetter struct {
	ID           omit.Val[string]                      `db:"id,pk"`
	Name         omit.Val[string]                      `db:"name"`
	Slug         omit.Val[string]                      `db:"slug"`
	Link         omit.Val[string]                      `db:"link"`
	Description  omit.Val[string]                      `db:"description"`
	FeatureImage omit.Val[string]                      `db:"feature_image"`
	Title        omit.Val[string]                      `db:"title"`
	Content      omitnull.Val[string]                  `db:"content"`
	Author       omitnull.Val[string]                  `db:"author"`
	Category     omit.Val[types.JSON[json.RawMessage]] `db:"category"`
	VideoURL     omitnull.Val[string]                  `db:"video_url"`
	CreatedAt    omit.Val[time.Time]                   `db:"created_at"`
	UpdatedAt    omit.Val[time.Time]                   `db:"updated_at"`
}

type newsColumnNames struct {
	ID           string
	Name         string
	Slug         string
	Link         string
	Description  string
	FeatureImage string
	Title        string
	Content      string
	Author       string
	Category     string
	VideoURL     string
	CreatedAt    string
	UpdatedAt    string
}

var NewsColumns = struct {
	ID           psql.Expression
	Name         psql.Expression
	Slug         psql.Expression
	Link         psql.Expression
	Description  psql.Expression
	FeatureImage psql.Expression
	Title        psql.Expression
	Content      psql.Expression
	Author       psql.Expression
	Category     psql.Expression
	VideoURL     psql.Expression
	CreatedAt    psql.Expression
	UpdatedAt    psql.Expression
}{
	ID:           psql.Quote("news", "id"),
	Name:         psql.Quote("news", "name"),
	Slug:         psql.Quote("news", "slug"),
	Link:         psql.Quote("news", "link"),
	Description:  psql.Quote("news", "description"),
	FeatureImage: psql.Quote("news", "feature_image"),
	Title:        psql.Quote("news", "title"),
	Content:      psql.Quote("news", "content"),
	Author:       psql.Quote("news", "author"),
	Category:     psql.Quote("news", "category"),
	VideoURL:     psql.Quote("news", "video_url"),
	CreatedAt:    psql.Quote("news", "created_at"),
	UpdatedAt:    psql.Quote("news", "updated_at"),
}

type newsWhere[Q psql.Filterable] struct {
	ID           psql.WhereMod[Q, string]
	Name         psql.WhereMod[Q, string]
	Slug         psql.WhereMod[Q, string]
	Link         psql.WhereMod[Q, string]
	Description  psql.WhereMod[Q, string]
	FeatureImage psql.WhereMod[Q, string]
	Title        psql.WhereMod[Q, string]
	Content      psql.WhereNullMod[Q, string]
	Author       psql.WhereNullMod[Q, string]
	Category     psql.WhereMod[Q, types.JSON[json.RawMessage]]
	VideoURL     psql.WhereNullMod[Q, string]
	CreatedAt    psql.WhereMod[Q, time.Time]
	UpdatedAt    psql.WhereMod[Q, time.Time]
}

func NewsWhere[Q psql.Filterable]() newsWhere[Q] {
	return newsWhere[Q]{
		ID:           psql.Where[Q, string](NewsColumns.ID),
		Name:         psql.Where[Q, string](NewsColumns.Name),
		Slug:         psql.Where[Q, string](NewsColumns.Slug),
		Link:         psql.Where[Q, string](NewsColumns.Link),
		Description:  psql.Where[Q, string](NewsColumns.Description),
		FeatureImage: psql.Where[Q, string](NewsColumns.FeatureImage),
		Title:        psql.Where[Q, string](NewsColumns.Title),
		Content:      psql.WhereNull[Q, string](NewsColumns.Content),
		Author:       psql.WhereNull[Q, string](NewsColumns.Author),
		Category:     psql.Where[Q, types.JSON[json.RawMessage]](NewsColumns.Category),
		VideoURL:     psql.WhereNull[Q, string](NewsColumns.VideoURL),
		CreatedAt:    psql.Where[Q, time.Time](NewsColumns.CreatedAt),
		UpdatedAt:    psql.Where[Q, time.Time](NewsColumns.UpdatedAt),
	}
}

// News begins a query on news
func News(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) NewsQuery {
	return NewsTable.Query(ctx, exec, mods...)
}

// FindNews retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindNews(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*NewsType, error) {
	if len(cols) == 0 {
		return NewsTable.Query(
			ctx, exec,
			SelectWhere.News.ID.EQ(IDPK),
		).One()
	}

	return NewsTable.Query(
		ctx, exec,
		SelectWhere.News.ID.EQ(IDPK),
		sm.Columns(NewsTable.Columns().Only(cols...)),
	).One()
}

// NewsExists checks the presence of a single record by primary key
func NewsExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return NewsTable.Query(
		ctx, exec,
		SelectWhere.News.ID.EQ(IDPK),
	).Exists()
}

// Update uses an executor to update the News
func (o *NewsType) Update(ctx context.Context, exec bob.Executor, cols ...string) (int64, error) {
	rowsAff, err := NewsTable.Update(ctx, exec, o, cols...)
	if err != nil {
		return rowsAff, err
	}

	return rowsAff, nil
}

// Delete deletes a single News record with an executor
func (o *NewsType) Delete(ctx context.Context, exec bob.Executor) (int64, error) {
	return NewsTable.Delete(ctx, exec, o)
}

// Reload refreshes the News using the executor
func (o *NewsType) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := NewsTable.Query(
		ctx, exec,
		SelectWhere.News.ID.EQ(o.ID),
	).One()
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

func (o NewsSlice) DeleteAll(ctx context.Context, exec bob.Executor) (int64, error) {
	return NewsTable.DeleteMany(ctx, exec, o...)
}

func (o NewsSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals NewsSetter) (int64, error) {
	rowsAff, err := NewsTable.UpdateMany(ctx, exec, &vals, o...)
	if err != nil {
		return rowsAff, err
	}

	return rowsAff, nil
}

func (o NewsSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	var mods []bob.Mod[*dialect.SelectQuery]

	IDPK := make([]string, len(o))

	for i, o := range o {
		IDPK[i] = o.ID
	}

	mods = append(mods,
		SelectWhere.News.ID.In(IDPK...),
	)

	o2, err := News(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, old := range o {
		for _, new := range o2 {
			if new.ID != old.ID {
				continue
			}

			*old = *new
			break
		}
	}

	return nil
}
