// Code generated by BobGen psql v0.21.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"encoding/json"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/types"
)

// NewsInfor is an object representing the database table.
type NewsInfor struct {
	ID           string                                `db:"id,pk" `
	Name         string                                `db:"name" `
	Slug         string                                `db:"slug" `
	Link         null.Val[string]                      `db:"link" `
	Description  string                                `db:"description" `
	FeatureImage string                                `db:"feature_image" `
	Title        string                                `db:"title" `
	Content      null.Val[string]                      `db:"content" `
	Author       null.Val[string]                      `db:"author" `
	Category     types.JSON[json.RawMessage]           `db:"category" `
	VideoURL     null.Val[string]                      `db:"video_url" `
	CreatedAt    time.Time                             `db:"created_at" `
	UpdatedAt    time.Time                             `db:"updated_at" `
	Labels       null.Val[types.JSON[json.RawMessage]] `db:"labels" `
}

// NewsInforSlice is an alias for a slice of pointers to NewsInfor.
// This should almost always be used instead of []*NewsInfor.
type NewsInforSlice []*NewsInfor

// NewsInforsTable contains methods to work with the news_infor table
var NewsInforsTable = psql.NewTablex[*NewsInfor, NewsInforSlice, *NewsInforSetter]("", "news_infor")

// NewsInforsQuery is a query on the news_infor table
type NewsInforsQuery = *psql.TableQuery[*NewsInfor, NewsInforSlice, *NewsInforSetter]

// NewsInforsStmt is a prepared statment on news_infor
type NewsInforsStmt = bob.QueryStmt[*NewsInfor, NewsInforSlice]

// NewsInforSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type NewsInforSetter struct {
	ID           omit.Val[string]                          `db:"id,pk"`
	Name         omit.Val[string]                          `db:"name"`
	Slug         omit.Val[string]                          `db:"slug"`
	Link         omitnull.Val[string]                      `db:"link"`
	Description  omit.Val[string]                          `db:"description"`
	FeatureImage omit.Val[string]                          `db:"feature_image"`
	Title        omit.Val[string]                          `db:"title"`
	Content      omitnull.Val[string]                      `db:"content"`
	Author       omitnull.Val[string]                      `db:"author"`
	Category     omit.Val[types.JSON[json.RawMessage]]     `db:"category"`
	VideoURL     omitnull.Val[string]                      `db:"video_url"`
	CreatedAt    omit.Val[time.Time]                       `db:"created_at"`
	UpdatedAt    omit.Val[time.Time]                       `db:"updated_at"`
	Labels       omitnull.Val[types.JSON[json.RawMessage]] `db:"labels"`
}

type newsInforColumnNames struct {
	ID           string
	Name         string
	Slug         string
	Link         string
	Description  string
	FeatureImage string
	Title        string
	Content      string
	Author       string
	Category     string
	VideoURL     string
	CreatedAt    string
	UpdatedAt    string
	Labels       string
}

var NewsInforColumns = struct {
	ID           psql.Expression
	Name         psql.Expression
	Slug         psql.Expression
	Link         psql.Expression
	Description  psql.Expression
	FeatureImage psql.Expression
	Title        psql.Expression
	Content      psql.Expression
	Author       psql.Expression
	Category     psql.Expression
	VideoURL     psql.Expression
	CreatedAt    psql.Expression
	UpdatedAt    psql.Expression
	Labels       psql.Expression
}{
	ID:           psql.Quote("news_infor", "id"),
	Name:         psql.Quote("news_infor", "name"),
	Slug:         psql.Quote("news_infor", "slug"),
	Link:         psql.Quote("news_infor", "link"),
	Description:  psql.Quote("news_infor", "description"),
	FeatureImage: psql.Quote("news_infor", "feature_image"),
	Title:        psql.Quote("news_infor", "title"),
	Content:      psql.Quote("news_infor", "content"),
	Author:       psql.Quote("news_infor", "author"),
	Category:     psql.Quote("news_infor", "category"),
	VideoURL:     psql.Quote("news_infor", "video_url"),
	CreatedAt:    psql.Quote("news_infor", "created_at"),
	UpdatedAt:    psql.Quote("news_infor", "updated_at"),
	Labels:       psql.Quote("news_infor", "labels"),
}

type newsInforWhere[Q psql.Filterable] struct {
	ID           psql.WhereMod[Q, string]
	Name         psql.WhereMod[Q, string]
	Slug         psql.WhereMod[Q, string]
	Link         psql.WhereNullMod[Q, string]
	Description  psql.WhereMod[Q, string]
	FeatureImage psql.WhereMod[Q, string]
	Title        psql.WhereMod[Q, string]
	Content      psql.WhereNullMod[Q, string]
	Author       psql.WhereNullMod[Q, string]
	Category     psql.WhereMod[Q, types.JSON[json.RawMessage]]
	VideoURL     psql.WhereNullMod[Q, string]
	CreatedAt    psql.WhereMod[Q, time.Time]
	UpdatedAt    psql.WhereMod[Q, time.Time]
	Labels       psql.WhereNullMod[Q, types.JSON[json.RawMessage]]
}

func NewsInforWhere[Q psql.Filterable]() newsInforWhere[Q] {
	return newsInforWhere[Q]{
		ID:           psql.Where[Q, string](NewsInforColumns.ID),
		Name:         psql.Where[Q, string](NewsInforColumns.Name),
		Slug:         psql.Where[Q, string](NewsInforColumns.Slug),
		Link:         psql.WhereNull[Q, string](NewsInforColumns.Link),
		Description:  psql.Where[Q, string](NewsInforColumns.Description),
		FeatureImage: psql.Where[Q, string](NewsInforColumns.FeatureImage),
		Title:        psql.Where[Q, string](NewsInforColumns.Title),
		Content:      psql.WhereNull[Q, string](NewsInforColumns.Content),
		Author:       psql.WhereNull[Q, string](NewsInforColumns.Author),
		Category:     psql.Where[Q, types.JSON[json.RawMessage]](NewsInforColumns.Category),
		VideoURL:     psql.WhereNull[Q, string](NewsInforColumns.VideoURL),
		CreatedAt:    psql.Where[Q, time.Time](NewsInforColumns.CreatedAt),
		UpdatedAt:    psql.Where[Q, time.Time](NewsInforColumns.UpdatedAt),
		Labels:       psql.WhereNull[Q, types.JSON[json.RawMessage]](NewsInforColumns.Labels),
	}
}

// NewsInfors begins a query on news_infor
func NewsInfors(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) NewsInforsQuery {
	return NewsInforsTable.Query(ctx, exec, mods...)
}

// FindNewsInfor retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindNewsInfor(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*NewsInfor, error) {
	if len(cols) == 0 {
		return NewsInforsTable.Query(
			ctx, exec,
			SelectWhere.NewsInfors.ID.EQ(IDPK),
		).One()
	}

	return NewsInforsTable.Query(
		ctx, exec,
		SelectWhere.NewsInfors.ID.EQ(IDPK),
		sm.Columns(NewsInforsTable.Columns().Only(cols...)),
	).One()
}

// NewsInforExists checks the presence of a single record by primary key
func NewsInforExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return NewsInforsTable.Query(
		ctx, exec,
		SelectWhere.NewsInfors.ID.EQ(IDPK),
	).Exists()
}

// Update uses an executor to update the NewsInfor
func (o *NewsInfor) Update(ctx context.Context, exec bob.Executor, cols ...string) (int64, error) {
	rowsAff, err := NewsInforsTable.Update(ctx, exec, o, cols...)
	if err != nil {
		return rowsAff, err
	}

	return rowsAff, nil
}

// Delete deletes a single NewsInfor record with an executor
func (o *NewsInfor) Delete(ctx context.Context, exec bob.Executor) (int64, error) {
	return NewsInforsTable.Delete(ctx, exec, o)
}

// Reload refreshes the NewsInfor using the executor
func (o *NewsInfor) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := NewsInforsTable.Query(
		ctx, exec,
		SelectWhere.NewsInfors.ID.EQ(o.ID),
	).One()
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

func (o NewsInforSlice) DeleteAll(ctx context.Context, exec bob.Executor) (int64, error) {
	return NewsInforsTable.DeleteMany(ctx, exec, o...)
}

func (o NewsInforSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals NewsInforSetter) (int64, error) {
	rowsAff, err := NewsInforsTable.UpdateMany(ctx, exec, &vals, o...)
	if err != nil {
		return rowsAff, err
	}

	return rowsAff, nil
}

func (o NewsInforSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	var mods []bob.Mod[*dialect.SelectQuery]

	IDPK := make([]string, len(o))

	for i, o := range o {
		IDPK[i] = o.ID
	}

	mods = append(mods,
		SelectWhere.NewsInfors.ID.In(IDPK...),
	)

	o2, err := NewsInfors(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, old := range o {
		for _, new := range o2 {
			if new.ID != old.ID {
				continue
			}

			*old = *new
			break
		}
	}

	return nil
}
