name: Go

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'core/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Build
        run: |
          cd core
          go build -v ./...
